// Material Design 3 inspired color tokens

export const md3 = {
  light: {
    primary: '#1B6C4A',
    onPrimary: '#FFFFFF',
    primaryContainer: '#A4F5C5',
    onPrimaryContainer: '#002113',
    secondary: '#4E6355',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D0E8D7',
    onSecondaryContainer: '#0B1F15',
    tertiary: '#3C6472',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BFEAF9',
    onTertiaryContainer: '#001F28',
    surface: '#F6FBF3',
    onSurface: '#181D19',
    surfaceVariant: '#DDE5DB',
    onSurfaceVariant: '#414942',
    surfaceContainer: '#EAEFE7',
    surfaceContainerHigh: '#E5EAE1',
    surfaceContainerLow: '#F0F5ED',
    outline: '#717971',
    outlineVariant: '#C1C9BF',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    inverseSurface: '#2C322D',
    inverseOnSurface: '#EDF2EA',
  },
  dark: {
    primary: '#88D9AA',
    onPrimary: '#003822',
    primaryContainer: '#005235',
    onPrimaryContainer: '#A4F5C5',
    secondary: '#B4CCBB',
    onSecondary: '#203529',
    secondaryContainer: '#364B3E',
    onSecondaryContainer: '#D0E8D7',
    tertiary: '#A4CEDD',
    onTertiary: '#043542',
    tertiaryContainer: '#224C59',
    onTertiaryContainer: '#BFEAF9',
    surface: '#101510',
    onSurface: '#DFE4DC',
    surfaceVariant: '#414942',
    onSurfaceVariant: '#C1C9BF',
    surfaceContainer: '#1C211C',
    surfaceContainerHigh: '#262B27',
    surfaceContainerLow: '#181D19',
    outline: '#8B938A',
    outlineVariant: '#414942',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    inverseSurface: '#DFE4DC',
    inverseOnSurface: '#2C322D',
  },
}

// Keep legacy export for any remaining template components
export default {
  light: {
    text: md3.light.onSurface,
    background: md3.light.surface,
    tint: md3.light.primary,
    tabIconDefault: md3.light.outline,
    tabIconSelected: md3.light.primary,
  },
  dark: {
    text: md3.dark.onSurface,
    background: md3.dark.surface,
    tint: md3.dark.primary,
    tabIconDefault: md3.dark.outline,
    tabIconSelected: md3.dark.primary,
  },
}
