// Material Design 3 inspired color tokens
// Brand blue: #072d5c (BlueWink dark navy)

export const md3 = {
  light: {
    primary: '#1D5BB7',
    onPrimary: '#FFFFFF',
    primaryContainer: '#D9E2FF',
    onPrimaryContainer: '#001947',
    secondary: '#565E71',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#DAE2F9',
    onSecondaryContainer: '#131C2B',
    tertiary: '#3C6472',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BFEAF9',
    onTertiaryContainer: '#001F28',
    surface: '#FAF9FD',
    onSurface: '#1A1B21',
    surfaceVariant: '#E1E2EC',
    onSurfaceVariant: '#44474F',
    surfaceContainer: '#EEEDF4',
    surfaceContainerHigh: '#E8E7EE',
    surfaceContainerLow: '#F4F3FA',
    outline: '#74777F',
    outlineVariant: '#C4C6D0',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    inverseSurface: '#2F3036',
    inverseOnSurface: '#F1F0F7',
  },
  dark: {
    primary: '#B0C6FF',
    onPrimary: '#002E69',
    primaryContainer: '#072D5C',
    onPrimaryContainer: '#D9E2FF',
    secondary: '#BEC6DC',
    onSecondary: '#283041',
    secondaryContainer: '#3E4759',
    onSecondaryContainer: '#DAE2F9',
    tertiary: '#A4CEDD',
    onTertiary: '#043542',
    tertiaryContainer: '#224C59',
    onTertiaryContainer: '#BFEAF9',
    surface: '#111318',
    onSurface: '#E2E2E9',
    surfaceVariant: '#44474F',
    onSurfaceVariant: '#C4C6D0',
    surfaceContainer: '#1D2024',
    surfaceContainerHigh: '#272A2F',
    surfaceContainerLow: '#181B1F',
    outline: '#8E9099',
    outlineVariant: '#44474F',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    inverseSurface: '#E2E2E9',
    inverseOnSurface: '#2F3036',
  },
}

// Keep legacy export for any remaining template components
export default {
  light: {
    text: md3.light.onSurface,
    background: md3.light.surface,
    tint: md3.light.primary,
    tabIconDefault: md3.light.outline,
    tabIconSelected: md3.light.primary,
  },
  dark: {
    text: md3.dark.onSurface,
    background: md3.dark.surface,
    tint: md3.dark.primary,
    tabIconDefault: md3.dark.outline,
    tabIconSelected: md3.dark.primary,
  },
}
